#!/bin/bash
# Generate machine-specific user configuration for Home Manager
# This script detects user/system info and generates user-config.nix
# Returns: Nix system identifier (e.g., "x86_64-linux") on stdout

set -e
set -u

# Color codes for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Detect user information
CURRENT_USER="${USER:-$(whoami)}"
HOME_DIR="${HOME:-/home/${CURRENT_USER}}"

# Detect system information
ARCH=$(uname -m)
HOSTNAME=$(hostname)
KERNEL=$(uname -r)

# Detect OS information
if [ -f /etc/os-release ]; then
    # shellcheck disable=SC1091
    . /etc/os-release
    OS_INFO="${PRETTY_NAME:-Unknown OS}"
else
    OS_INFO="Unknown OS"
fi

# Validate required values
if [ -z "${CURRENT_USER}" ]; then
    echo -e "${RED}ERROR: Could not detect username${NC}" >&2
    exit 1
fi

if [ -z "${HOME_DIR}" ]; then
    echo -e "${RED}ERROR: Could not detect home directory${NC}" >&2
    exit 1
fi

# Map architecture to Nix system identifier
case "${ARCH}" in
    x86_64)
        NIX_SYSTEM="x86_64-linux"
        ;;
    aarch64|arm64)
        NIX_SYSTEM="aarch64-linux"
        ;;
    *)
        echo -e "${RED}ERROR: Unsupported architecture: ${ARCH}${NC}" >&2
        echo "Supported architectures: x86_64, aarch64, arm64" >&2
        exit 1
        ;;
esac

# Determine output file path
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
USER_CONFIG_FILE="${SCRIPT_DIR}/../home-manager/user-config.nix"

# Generate user-config.nix
cat > "${USER_CONFIG_FILE}" << NIXEOF
# Auto-generated machine-specific configuration
# ============================================
# DO NOT EDIT MANUALLY - This file is automatically generated
# DO NOT COMMIT - This file is git-ignored and machine-specific
#
# Generated: $(date -u +"%Y-%m-%d %H:%M:%S UTC")
#
# Machine Information:
#   Hostname: ${HOSTNAME}
#   System: ${NIX_SYSTEM}
#   Architecture: ${ARCH}
#   OS: ${OS_INFO}
#   Kernel: ${KERNEL}
#
# User Information:
#   Username: ${CURRENT_USER}
#   Home: ${HOME_DIR}

{
  # User configuration
  home.username = "${CURRENT_USER}";
  home.homeDirectory = "${HOME_DIR}";
}
NIXEOF

# Verify file was created successfully
if [ ! -f "${USER_CONFIG_FILE}" ]; then
    echo -e "${RED}ERROR: Failed to generate ${USER_CONFIG_FILE}${NC}" >&2
    exit 1
fi

# Output Nix system identifier for Makefile/scripts to capture
echo "${NIX_SYSTEM}"
