{
  description = "Home Manager configuration for Ubuntu server";

  inputs = {
    nixpkgs.url = "github:nixos/nixpkgs/nixos-24.05";
    home-manager = {
      url = "github:nix-community/home-manager/release-24.05";
      inputs.nixpkgs.follows = "nixpkgs";
    };
  };

  outputs = { nixpkgs, home-manager, ... }:
    let
      # Simple function to create Home Manager configuration for a given system
      mkHomeConfiguration = system:
        home-manager.lib.homeManagerConfiguration {
          pkgs = nixpkgs.legacyPackages.${system};
          modules = [ ./home.nix ];
        };
    in {
      homeConfigurations = {
        # Architecture-based configurations
        # User-specific values (username, homeDirectory) are imported from user-config.nix
        # which is auto-generated by scripts/generate-user-config.sh
        
        "x86_64-linux" = mkHomeConfiguration "x86_64-linux";
        "aarch64-linux" = mkHomeConfiguration "aarch64-linux";
      };
    };
}
