# Auto-generated machine-specific configuration
# ============================================
# This file is automatically generated by scripts/generate-user-config.sh
# Default values are provided below for initial setup
#
# IMPORTANT: This file is tracked in Git with default values
# The generation script will overwrite this with your actual system values
# Do not edit manually - changes will be overwritten on next generation

{
  # User configuration
  home.username = "tagpro";
  home.homeDirectory = "/home/tagpro";
}
