#!/bin/bash
#==============================================================================
# GitHub CLI (gh) Installer
#
# GitHub's official command line tool
# https://github.com/cli/cli
#
# Installed via apt repository (not GitHub releases)
#
# Usage: ./github-cli.sh [install|update|verify|version]
#==============================================================================

set -e
set -u
set -o pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"

source "${SCRIPT_DIR}/../lib/core.sh"
source "${SCRIPT_DIR}/../lib/lock.sh"
source "${SCRIPT_DIR}/../lib/health.sh"
source "${SCRIPT_DIR}/../lib/dryrun.sh"

PACKAGE_NAME="gh"

is_installed() { command_exists gh; }

get_installed_version() {
    if is_installed; then
        gh --version 2>/dev/null | grep -oE '[0-9]+\.[0-9]+\.[0-9]+' | head -1
    fi
}

# Check if GitHub CLI repository is configured
is_repo_configured() {
    [[ -f /etc/apt/sources.list.d/github-cli.list ]]
}

# Add GitHub CLI repository
add_gh_repo() {
    log_info "Adding GitHub CLI repository..."

    if ! is_dry_run; then
        # Install prerequisites
        sudo apt-get update -qq
        sudo apt-get install -y -qq curl gpg

        # Add GPG key
        sudo mkdir -p -m 755 /etc/apt/keyrings
        curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo tee /etc/apt/keyrings/githubcli-archive-keyring.gpg > /dev/null
        sudo chmod go+r /etc/apt/keyrings/githubcli-archive-keyring.gpg

        # Add repository
        echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | \
            sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null

        sudo apt-get update -qq
    else
        echo "[DRY-RUN] Would add GitHub CLI repository"
    fi

    log_success "GitHub CLI repository added"
}

do_install() {
    log_info "Installing GitHub CLI..."

    # Add repository if not configured
    if ! is_repo_configured; then
        add_gh_repo
    fi

    # Install gh
    apt_or_print install -y -qq gh

    # Update lock file
    local version
    version=$(get_installed_version)
    if [[ -n "$version" ]]; then
        update_lock "$PACKAGE_NAME" "$version"
    fi

    log_success "GitHub CLI installed"
}

verify() {
    if ! is_installed; then
        health_fail "$PACKAGE_NAME" "not installed"
        return 1
    fi
    health_pass "$PACKAGE_NAME" "v$(get_installed_version)"
    return 0
}

create_shell_config() {
    local config_file="${HOME}/.config/shell/38-github-cli.sh"
    mkdir -p "$(dirname "$config_file")" 2>/dev/null || true
    write_or_print "$config_file" '# GitHub CLI configuration
# Generated by github-cli.sh

# gh aliases
alias ghpr="gh pr"
alias ghprc="gh pr create"
alias ghprv="gh pr view"
alias ghprl="gh pr list"
alias ghi="gh issue"
alias ghic="gh issue create"
alias ghiv="gh issue view"
alias ghil="gh issue list"
'
}

main() {
    parse_dry_run_flag "$@"
    local action="${1:-install}"

    [[ -f "${PROJECT_ROOT}/config.env" ]] && source "${PROJECT_ROOT}/config.env"
    [[ "${PACKAGE_GITHUB_CLI_ENABLED:-true}" != "true" ]] && { log_info "GitHub CLI disabled"; return 0; }

    case "$action" in
        install)
            if is_installed; then
                log_success "GitHub CLI already installed: v$(get_installed_version)"
            else
                do_install
            fi
            create_shell_config
            verify
            ;;
        update)
            log_info "Updating GitHub CLI via apt..."
            apt_or_print update -qq
            apt_or_print upgrade -y -qq gh
            local version=$(get_installed_version)
            [[ -n "$version" ]] && update_lock "$PACKAGE_NAME" "$version"
            verify
            ;;
        verify) verify ;;
        version) is_installed && get_installed_version || { echo "not installed"; return 1; } ;;
        *) echo "Usage: $0 [install|update|verify|version] [--dry-run]"; exit 1 ;;
    esac

    is_dry_run && print_dry_run_summary || true
}

[[ "${BASH_SOURCE[0]}" == "${0}" ]] && main "$@"
