#!/bin/bash
#==============================================================================
# lazygit Installer
#
# A simple terminal UI for git commands
# https://github.com/jesseduffield/lazygit
#
# Uses GitHub releases (downloads latest)
#
# Usage: ./lazygit.sh [install|update|verify|version]
#==============================================================================

set -e
set -u
set -o pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"

source "${SCRIPT_DIR}/../lib/core.sh"
source "${SCRIPT_DIR}/../lib/health.sh"
source "${SCRIPT_DIR}/../lib/dryrun.sh"

PACKAGE_NAME="lazygit"
INSTALL_PATH="/usr/local/bin/lazygit"

is_installed() { command_exists lazygit; }

get_installed_version() {
    if is_installed; then
        lazygit --version 2>/dev/null | grep -oE 'version=([0-9.]+)' | cut -d= -f2 | head -1
    fi
}

get_latest_version() {
    curl -fsSL "https://api.github.com/repos/jesseduffield/lazygit/releases/latest" 2>/dev/null | \
        grep '"tag_name"' | sed -E 's/.*"v([^"]+)".*/\1/'
}

do_install() {
    log_info "Installing lazygit..."

    if is_dry_run; then
        echo "[DRY-RUN] Would download and install lazygit"
        return 0
    fi

    local arch=$(uname -m)
    # lazygit uses x86_64 and arm64
    [[ "$arch" == "aarch64" ]] && arch="arm64"

    local version=$(get_latest_version)
    local tmp_dir=$(mktemp -d)
    trap "rm -rf $tmp_dir" EXIT

    local url="https://github.com/jesseduffield/lazygit/releases/download/v${version}/lazygit_${version}_Linux_${arch}.tar.gz"

    curl -fsSL "$url" -o "${tmp_dir}/lazygit.tar.gz"
    tar -xzf "${tmp_dir}/lazygit.tar.gz" -C "$tmp_dir"
    sudo install -m 755 "${tmp_dir}/lazygit" "$INSTALL_PATH"

    log_success "lazygit installed"
}

verify() {
    if ! is_installed; then
        health_fail "$PACKAGE_NAME" "not installed"
        return 1
    fi
    health_pass "$PACKAGE_NAME" "v$(get_installed_version)"
    return 0
}

create_shell_config() {
    local config_file="${HOME}/.config/shell/35-lazygit.sh"
    mkdir -p "$(dirname "$config_file")" 2>/dev/null || true
    write_or_print "$config_file" '# lazygit configuration
# Generated by lazygit.sh

alias lg="lazygit"
'
}

main() {
    parse_dry_run_flag "$@"
    local action="${1:-install}"

    [[ -f "${PROJECT_ROOT}/config.env" ]] && source "${PROJECT_ROOT}/config.env"
    [[ "${PACKAGE_LAZYGIT_ENABLED:-true}" != "true" ]] && { log_info "lazygit disabled"; return 0; }

    case "$action" in
        install|update)
            if is_installed && [[ "$action" == "install" ]]; then
                log_success "lazygit already installed: v$(get_installed_version)"
            else
                do_install
            fi
            create_shell_config
            verify
            ;;
        verify) verify ;;
        version) is_installed && get_installed_version || { echo "not installed"; return 1; } ;;
        *) echo "Usage: $0 [install|update|verify|version] [--dry-run]"; exit 1 ;;
    esac
}

[[ "${BASH_SOURCE[0]}" == "${0}" ]] && main "$@"
