#!/bin/bash
#==============================================================================
# lazygit Installer
#
# A simple terminal UI for git commands
# https://github.com/jesseduffield/lazygit
#
# Usage: ./lazygit.sh [install|update|verify|version]
#==============================================================================

set -e
set -u
set -o pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"

# Source shared libraries
source "${SCRIPT_DIR}/../lib/core.sh"
source "${SCRIPT_DIR}/../lib/version.sh"
source "${SCRIPT_DIR}/../lib/lock.sh"
source "${SCRIPT_DIR}/../lib/health.sh"
source "${SCRIPT_DIR}/../lib/dryrun.sh"

#==============================================================================
# Package Configuration
#==============================================================================

PACKAGE_NAME="lazygit"
GITHUB_REPO="jesseduffield/lazygit"
INSTALL_PATH="/usr/local/bin/lazygit"

#==============================================================================
# Functions
#==============================================================================

is_installed() {
    command_exists lazygit
}

get_installed_version() {
    if is_installed; then
        lazygit --version 2>/dev/null | grep -oE 'version=([0-9.]+)' | cut -d= -f2 | head -1
    fi
}

get_desired_version() {
    if [[ -f "${PROJECT_ROOT}/config.env" ]]; then
        source "${PROJECT_ROOT}/config.env"
    fi

    local version="${PACKAGE_LAZYGIT_VERSION:-latest}"

    if [[ "$version" == "latest" ]]; then
        resolve_version "latest" "$GITHUB_REPO"
    else
        echo "$version"
    fi
}

do_install() {
    local version="$1"
    local arch
    arch=$(get_github_arch)

    # lazygit uses different arch naming
    case "$arch" in
        amd64|x86_64) arch="x86_64" ;;
        arm64) arch="arm64" ;;
    esac

    log_info "Installing lazygit v${version}..."

    local url="https://github.com/${GITHUB_REPO}/releases/download/v${version}/lazygit_${version}_Linux_${arch}.tar.gz"

    local tmp_dir
    tmp_dir=$(mktemp -d)
    trap "rm -rf $tmp_dir" EXIT

    download_or_print "$url" "${tmp_dir}/lazygit.tar.gz"

    if ! is_dry_run; then
        tar -xzf "${tmp_dir}/lazygit.tar.gz" -C "$tmp_dir"
        sudo install -m 755 "${tmp_dir}/lazygit" "$INSTALL_PATH"
    fi

    update_lock "$PACKAGE_NAME" "$version"
    log_success "lazygit v${version} installed"
}

verify() {
    if ! is_installed; then
        health_fail "$PACKAGE_NAME" "not installed"
        return 1
    fi

    local version
    version=$(get_installed_version)
    health_pass "$PACKAGE_NAME" "v${version}"
    return 0
}

create_shell_config() {
    local config_dir="${HOME}/.config/shell"
    local config_file="${config_dir}/35-lazygit.sh"

    mkdir -p "$config_dir" 2>/dev/null || true

    local content="# lazygit configuration
# Generated by lazygit.sh

alias lg='lazygit'
"
    write_or_print "$config_file" "$content"
}

#==============================================================================
# Main
#==============================================================================

main() {
    parse_dry_run_flag "$@"

    local action="${1:-install}"

    # Check if enabled
    if [[ -f "${PROJECT_ROOT}/config.env" ]]; then
        source "${PROJECT_ROOT}/config.env"
    fi
    if [[ "${PACKAGE_LAZYGIT_ENABLED:-true}" != "true" ]]; then
        log_info "lazygit is disabled in config"
        return 0
    fi

    case "$action" in
        install|update)
            local desired_version
            desired_version=$(get_desired_version)

            if is_installed; then
                local current_version
                current_version=$(get_installed_version)

                if needs_update "$current_version" "$desired_version"; then
                    log_info "Updating lazygit: v${current_version} -> v${desired_version}"
                    do_install "$desired_version"
                else
                    log_success "lazygit v${current_version} is up to date"
                fi
            else
                do_install "$desired_version"
            fi

            create_shell_config
            verify
            ;;
        verify)
            verify
            ;;
        version)
            if is_installed; then
                get_installed_version
            else
                echo "not installed"
                return 1
            fi
            ;;
        *)
            echo "Usage: $0 [install|update|verify|version] [--dry-run]"
            exit 1
            ;;
    esac

    if is_dry_run; then
        print_dry_run_summary
    fi
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    main "$@"
fi
