#!/bin/bash
#==============================================================================
# Starship Installer
#
# The minimal, blazing-fast, and infinitely customizable prompt
# https://starship.rs
#
# Uses official installer: curl -sS https://starship.rs/install.sh | sh
#
# Usage: ./starship.sh [install|update|verify|version]
#==============================================================================

set -e
set -u
set -o pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"

source "${SCRIPT_DIR}/../lib/core.sh"
source "${SCRIPT_DIR}/../lib/health.sh"
source "${SCRIPT_DIR}/../lib/dryrun.sh"

PACKAGE_NAME="starship"

# Starship installs to ~/.local/bin - ensure it's in PATH for detection
[[ -d "${HOME}/.local/bin" ]] && export PATH="${HOME}/.local/bin:${PATH}"

# Source shell config if it exists (for PATH setup)
[[ -f "${HOME}/.zsh_custom_config" ]] && source "${HOME}/.zsh_custom_config"

is_installed() { command_exists starship; }

get_installed_version() {
    if is_installed; then
        starship --version 2>/dev/null | grep -oE '[0-9]+\.[0-9]+\.[0-9]+' | head -1
    fi
}

do_install() {
    log_info "Installing starship via official installer..."

    if is_dry_run; then
        echo "[DRY-RUN] Would run: curl -sS https://starship.rs/install.sh | sh -s -- -y -b ~/.local/bin"
        return 0
    fi

    # Install to ~/.local/bin (user-local, no sudo needed)
    mkdir -p "${HOME}/.local/bin"
    curl -sS https://starship.rs/install.sh | sh -s -- -y -b "${HOME}/.local/bin"

    log_success "starship installed"
}

verify() {
    if ! is_installed; then
        health_fail "$PACKAGE_NAME" "not installed"
        return 1
    fi
    health_pass "$PACKAGE_NAME" "v$(get_installed_version)"
    return 0
}

create_shell_config() {
    local config_file="${HOME}/.config/shell/70-starship.sh"
    mkdir -p "$(dirname "$config_file")" 2>/dev/null || true
    write_or_print "$config_file" '# Starship prompt
# Generated by starship.sh

if command -v starship &> /dev/null; then
    eval "$(starship init zsh)"
fi
'
}

main() {
    parse_dry_run_flag "$@"
    local action="${1:-install}"

    [[ -f "${PROJECT_ROOT}/config.env" ]] && source "${PROJECT_ROOT}/config.env"
    [[ "${PACKAGE_STARSHIP_ENABLED:-true}" != "true" ]] && { log_info "starship disabled"; return 0; }

    case "$action" in
        install|update)
            if is_installed && [[ "$action" == "install" ]]; then
                log_success "starship already installed: v$(get_installed_version)"
            else
                do_install
            fi
            create_shell_config
            verify
            ;;
        verify) verify ;;
        version) is_installed && get_installed_version || { echo "not installed"; return 1; } ;;
        *) echo "Usage: $0 [install|update|verify|version] [--dry-run]"; exit 1 ;;
    esac
}

[[ "${BASH_SOURCE[0]}" == "${0}" ]] && main "$@"
