#!/bin/bash
#==============================================================================
# Zellij Installer
#
# A terminal workspace with batteries included
# https://zellij.dev
#
# Uses official installer from GitHub releases
#
# Usage: ./zellij.sh [install|update|verify|version]
#==============================================================================

set -e
set -u
set -o pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"

source "${SCRIPT_DIR}/../lib/core.sh"
source "${SCRIPT_DIR}/../lib/health.sh"
source "${SCRIPT_DIR}/../lib/dryrun.sh"

PACKAGE_NAME="zellij"
INSTALL_PATH="/usr/local/bin/zellij"

is_installed() { command_exists zellij; }

get_installed_version() {
    if is_installed; then
        zellij --version 2>/dev/null | grep -oE '[0-9]+\.[0-9]+\.[0-9]+' | head -1
    fi
}

do_install() {
    log_info "Installing zellij..."

    if is_dry_run; then
        echo "[DRY-RUN] Would download and install zellij"
        return 0
    fi

    local arch=$(uname -m)
    # zellij uses x86_64 and aarch64
    [[ "$arch" == "arm64" ]] && arch="aarch64"

    local tmp_dir=$(mktemp -d)
    trap "rm -rf $tmp_dir" EXIT

    # Get latest release URL
    local url="https://github.com/zellij-org/zellij/releases/latest/download/zellij-${arch}-unknown-linux-musl.tar.gz"

    curl -fsSL "$url" -o "${tmp_dir}/zellij.tar.gz"
    tar -xzf "${tmp_dir}/zellij.tar.gz" -C "$tmp_dir"
    sudo install -m 755 "${tmp_dir}/zellij" "$INSTALL_PATH"

    log_success "zellij installed"
}

verify() {
    if ! is_installed; then
        health_fail "$PACKAGE_NAME" "not installed"
        return 1
    fi
    health_pass "$PACKAGE_NAME" "v$(get_installed_version)"
    return 0
}

create_shell_config() {
    local config_file="${HOME}/.config/shell/45-zellij.sh"
    mkdir -p "$(dirname "$config_file")" 2>/dev/null || true
    write_or_print "$config_file" '# Zellij terminal multiplexer
# Generated by zellij.sh

alias zj="zellij"
'
}

main() {
    parse_dry_run_flag "$@"
    local action="${1:-install}"

    [[ -f "${PROJECT_ROOT}/config.env" ]] && source "${PROJECT_ROOT}/config.env"
    [[ "${PACKAGE_ZELLIJ_ENABLED:-true}" != "true" ]] && { log_info "zellij disabled"; return 0; }

    case "$action" in
        install|update)
            if is_installed && [[ "$action" == "install" ]]; then
                log_success "zellij already installed: v$(get_installed_version)"
            else
                do_install
            fi
            create_shell_config
            verify
            ;;
        verify) verify ;;
        version) is_installed && get_installed_version || { echo "not installed"; return 1; } ;;
        *) echo "Usage: $0 [install|update|verify|version] [--dry-run]"; exit 1 ;;
    esac
}

[[ "${BASH_SOURCE[0]}" == "${0}" ]] && main "$@"
