#!/bin/bash
#==============================================================================
# Zoxide Installer
#
# A smarter cd command
# https://github.com/ajeetdsouza/zoxide
#
# Uses official installer: curl -sSfL https://raw.githubusercontent.com/ajeetdsouza/zoxide/main/install.sh | sh
#
# Usage: ./zoxide.sh [install|update|verify|version]
#==============================================================================

set -e
set -u
set -o pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"

source "${SCRIPT_DIR}/../lib/core.sh"
source "${SCRIPT_DIR}/../lib/health.sh"
source "${SCRIPT_DIR}/../lib/dryrun.sh"

PACKAGE_NAME="zoxide"

# zoxide official installer installs to ~/.local/bin
# Ensure it's in PATH for detection
[[ -d "${HOME}/.local/bin" ]] && export PATH="${HOME}/.local/bin:${PATH}"

# Source shell config if it exists (for PATH setup)
[[ -f "${HOME}/.zsh_custom_config" ]] && source "${HOME}/.zsh_custom_config"

is_installed() { command_exists zoxide; }

get_installed_version() {
    if is_installed; then
        zoxide --version 2>/dev/null | grep -oE '[0-9]+\.[0-9]+\.[0-9]+' | head -1
    fi
}

do_install() {
    log_info "Installing zoxide via official installer..."

    if is_dry_run; then
        echo "[DRY-RUN] Would run: curl -sSfL https://raw.githubusercontent.com/ajeetdsouza/zoxide/main/install.sh | sh"
        return 0
    fi

    curl -sSfL https://raw.githubusercontent.com/ajeetdsouza/zoxide/main/install.sh | sh

    log_success "zoxide installed"
}

verify() {
    if ! is_installed; then
        health_fail "$PACKAGE_NAME" "not installed"
        return 1
    fi
    health_pass "$PACKAGE_NAME" "v$(get_installed_version)"
    return 0
}

create_shell_config() {
    local config_file="${HOME}/.config/shell/40-zoxide.sh"
    mkdir -p "$(dirname "$config_file")" 2>/dev/null || true
    write_or_print "$config_file" '# Zoxide - smarter cd
# Generated by zoxide.sh

if command -v zoxide &> /dev/null; then
    eval "$(zoxide init zsh)"
    alias cd="z"
fi
'
}

main() {
    parse_dry_run_flag "$@"
    local action="${1:-install}"

    [[ -f "${PROJECT_ROOT}/config.env" ]] && source "${PROJECT_ROOT}/config.env"
    [[ "${PACKAGE_ZOXIDE_ENABLED:-true}" != "true" ]] && { log_info "zoxide disabled"; return 0; }

    case "$action" in
        install|update)
            if is_installed && [[ "$action" == "install" ]]; then
                log_success "zoxide already installed: v$(get_installed_version)"
            else
                do_install
            fi
            create_shell_config
            verify
            ;;
        verify) verify ;;
        version) is_installed && get_installed_version || { echo "not installed"; return 1; } ;;
        *) echo "Usage: $0 [install|update|verify|version] [--dry-run]"; exit 1 ;;
    esac
}

[[ "${BASH_SOURCE[0]}" == "${0}" ]] && main "$@"
