#!/bin/bash
#==============================================================================
# Zoxide Installer
#
# A smarter cd command, inspired by z and autojump
# https://github.com/ajeetdsouza/zoxide
#
# Usage: ./zoxide.sh [install|update|verify|version]
#==============================================================================

set -e
set -u
set -o pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"

source "${SCRIPT_DIR}/../lib/core.sh"
source "${SCRIPT_DIR}/../lib/version.sh"
source "${SCRIPT_DIR}/../lib/lock.sh"
source "${SCRIPT_DIR}/../lib/health.sh"
source "${SCRIPT_DIR}/../lib/dryrun.sh"

PACKAGE_NAME="zoxide"
GITHUB_REPO="ajeetdsouza/zoxide"
INSTALL_PATH="/usr/local/bin/zoxide"

is_installed() { command_exists zoxide; }

get_installed_version() {
    if is_installed; then
        zoxide --version 2>/dev/null | grep -oE '[0-9]+\.[0-9]+\.[0-9]+' | head -1
    fi
}

get_desired_version() {
    [[ -f "${PROJECT_ROOT}/config.env" ]] && source "${PROJECT_ROOT}/config.env"
    local version="${PACKAGE_ZOXIDE_VERSION:-latest}"
    [[ "$version" == "latest" ]] && resolve_version "latest" "$GITHUB_REPO" || echo "$version"
}

do_install() {
    local version="$1"
    local arch=$(get_github_arch)

    log_info "Installing zoxide v${version}..."

    # zoxide naming: zoxide-VERSION-ARCH-unknown-linux-musl.tar.gz
    local url="https://github.com/${GITHUB_REPO}/releases/download/v${version}/zoxide-${version}-${arch}-unknown-linux-musl.tar.gz"

    local tmp_dir=$(mktemp -d)
    trap "rm -rf $tmp_dir" EXIT

    download_or_print "$url" "${tmp_dir}/zoxide.tar.gz"

    if ! is_dry_run; then
        tar -xzf "${tmp_dir}/zoxide.tar.gz" -C "$tmp_dir"
        sudo install -m 755 "${tmp_dir}/zoxide" "$INSTALL_PATH"
    fi

    update_lock "$PACKAGE_NAME" "$version"
    log_success "zoxide v${version} installed"
}

verify() {
    if ! is_installed; then
        health_fail "$PACKAGE_NAME" "not installed"
        return 1
    fi
    health_pass "$PACKAGE_NAME" "v$(get_installed_version)"
    return 0
}

create_shell_config() {
    local config_file="${HOME}/.config/shell/75-zoxide.sh"
    mkdir -p "$(dirname "$config_file")" 2>/dev/null || true
    write_or_print "$config_file" '# Zoxide configuration
# Generated by zoxide.sh

if command -v zoxide &> /dev/null; then
    eval "$(zoxide init zsh)"
fi
'
}

main() {
    parse_dry_run_flag "$@"
    local action="${1:-install}"

    [[ -f "${PROJECT_ROOT}/config.env" ]] && source "${PROJECT_ROOT}/config.env"
    [[ "${PACKAGE_ZOXIDE_ENABLED:-true}" != "true" ]] && { log_info "zoxide disabled"; return 0; }

    case "$action" in
        install|update)
            local desired=$(get_desired_version)
            if is_installed; then
                local current=$(get_installed_version)
                needs_update "$current" "$desired" && do_install "$desired" || log_success "zoxide v${current} up to date"
            else
                do_install "$desired"
            fi
            create_shell_config
            verify
            ;;
        verify) verify ;;
        version) is_installed && get_installed_version || { echo "not installed"; return 1; } ;;
        *) echo "Usage: $0 [install|update|verify|version] [--dry-run]"; exit 1 ;;
    esac

    is_dry_run && print_dry_run_summary
}

[[ "${BASH_SOURCE[0]}" == "${0}" ]] && main "$@"
